### ISSUE TITLE
setup_postgresql fails, nc command not found

### ISSUE THREAD

**Issue by jonotron** [wmarinho/docker-pentaho#6]
When I try running this image with an external postgres server I see the following error

```
/opt/pentaho/scripts/setup_postgresql.sh: 28: /opt/pentaho/scripts/setup_postgresql.sh: nc: not found
```

If I shell into the container and try running `nc`, it is not found

**Comment by wmarinho** [comment]
Hi @jonotron, yeah. I've fixed only in master branch adding netcat (now 5.4 too). Which branch are you running?

**Comment by jonotron** [comment]
I was running `wmarinho/pentaho-biserver:5.4`

**Comment by wmarinho** [comment]
Fixed. Try again, please.

**Comment by jonotron** [comment]
Thanks for the fast fix. Seems to work now :)
